<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Simmering" name="Default test" tests="12" failures="1" timestamp="6 Nov 2019 07:11:55 GMT" time="0.069" errors="0">
  <testcase name="LoginAPIHomeLoan" time="0.004" classname="test.day4"/>
  <testcase name="MobileLoginHomeLoan" time="0.006" classname="test.day4"/>
  <testcase name="WebloginHomeLoan" time="0.001" classname="test.day4">
    <skipped/>
  </testcase> <!-- WebloginHomeLoan -->
  <testcase name="ploan" time="0.001" classname="test.day2"/>
  <testcase name="MobilesignoutcarLoan" time="0.001" classname="test.day3"/>
  <testcase name="MobilesignoutcarLoan" time="0.003" classname="test.day3"/>
  <testcase name="MobilesignoutcarLoan" time="0.002" classname="test.day3"/>
  <testcase name="WebloginCarLoan" time="0.001" classname="test.day3">
    <skipped/>
  </testcase> <!-- WebloginCarLoan -->
  <testcase name="MobileLogincarLoan" time="0.002" classname="test.day3"/>
  <testcase name="APIcarLoan" time="0.0" classname="test.day3">
    <skipped/>
  </testcase> <!-- APIcarLoan -->
  <testcase name="Demo" time="0.004" classname="test.day1">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:89)
	at org.testng.Assert.failNotEquals(Assert.java:489)
	at org.testng.Assert.assertTrue(Assert.java:37)
	at org.testng.Assert.assertTrue(Assert.java:47)
	at test.day1.Demo(day1.java:22)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:715)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:907)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1237)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:51)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:85)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1197)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1122)
	at org.testng.TestNG.run(TestNG.java:1030)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- Demo -->
  <testcase name="SecondTest" time="0.002" classname="test.day1"/>
</testsuite> <!-- Default test -->
